---

# Backup Image Docker-Compose file.
#
# You can control some of the behaviour of the build
# with environment variables: -
#
# - IMAGE_TAG The backup image version tag
#             (default latest)
#
# i.e.: -
#
#   IMAGE_TAG=stable docker-compose build
#   IMAGE_TAG=stable docker-compose push

version: '3.6'

services:

  postgresql-backup:
    build:
      context: .
    image: "informaticsmatters/sql-backup:${IMAGE_TAG:-latest}"
    container_name: sql-backup
