---

# An example gluster-like template for the backup and recovery volumes.

kind: Template
apiVersion: v1
metadata:
  name: infra-persistence-dynamic
  annotations:
    description: Infrastructure Persistence using dynamic provisioning
    tags: infra,pv,pvc
labels:
  template: infra-pvc-dynamic

parameters:

- name: STORAGE_CLASS
  value: glusterfs-storage

- name: BACKUP_VOLUME_NAME
  value: backup-claim
- name: BACKUP_VOLUME_SIZE
  value: 125Gi

objects:

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${BACKUP_VOLUME_NAME}
    labels:
      application: backup
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: "${BACKUP_VOLUME_SIZE}"
    storageClassName: ${STORAGE_CLASS}
