---

# Example postgres database backup deployments.
#
# A series of CronJob templates to demonstrate the multi-stage
# feature of the backup image. One CronJob (hourly)
# Makes new backups. Three other CronJopbs (daily, weekly, monthly)
# copy the oldest backup pof the prior type maintaining hourly,
# daily, weekly and monthly directories of backup files.
#
# oc process -f backup.yaml | oc create -f -
# oc delete job --selector template=postgreslq-backup

kind: Template
apiVersion: v1
metadata:
  name: mysql-backup
  annotations:
    description: MySQL Backup Template
    tags: mysql,backup,recovery
labels:
  template: mysql-backup
  app: mysql-backup

parameters:

- name: BACKUP_IMAGE
  value: 'informaticsmatters/sql-backup:stable'

objects:

# The HOURLY CronJob (running at HH:07).
# This job will create new postgres backups
# Keeping the last 24 backups in the directory /backup/hourly
- kind: CronJob
  apiVersion: batch/v2alpha1
  metadata:
    name: mysql-backup-hourly
  spec:
    schedule: '7 * * * *'
    startingDeadlineSeconds: 180
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              name: mysql-backup
          spec:
            # Application containers
            containers:
            - image: ${BACKUP_IMAGE}
              name: mysql-backup
              imagePullPolicy: Always
              volumeMounts:
              - name: mysql-backup-data
                mountPath: /backup

              env:
              - name: BACKUP_TYPE
                value: hourly
              - name: BACKUP_COUNT
                value: '24'

              - name: MSHOST
                value: db-mysql
              - name: MSUSER
                valueFrom:
                  secretKeyRef:
                    name: mysql-secrets
                    key: database-admin-user
              - name: MSPASS
                valueFrom:
                  secretKeyRef:
                    name: mysql-secrets
                    key: database-admin-pass

            volumes:
            - name: mysql-backup-data
              persistentVolumeClaim:
                claimName: mysql-backup-claim
            restartPolicy: Never

# The DAILY CronJob (at 00:55)
# This job will copy the oldest hourly backup (when there are 24)
# Keeping the last 6 backups in the directory /backup/daily
- kind: CronJob
  apiVersion: batch/v2alpha1
  metadata:
    name: mysql-backup-daily
  spec:
    schedule: '55 0 * * *'
    startingDeadlineSeconds: 180
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              name: backup-daily
          spec:
            # Application containers
            containers:
            - image: ${BACKUP_IMAGE}
              name: mysql-backup
              imagePullPolicy: Always
              volumeMounts:
              - name: mysql-backup-data
                mountPath: /backup

              env:
              - name: BACKUP_TYPE
                value: daily
              - name: BACKUP_COUNT
                value: '6'
              - name: BACKUP_PRIOR_TYPE
                value: hourly
              - name: BACKUP_PRIOR_COUNT
                value: '24'

            volumes:
            - name: mysql-backup-data
              persistentVolumeClaim:
                claimName: mysql-backup-claim
            restartPolicy: Never

# The WEEKLY CronJob (at 00:50 on Sunday)
# This job will copy the oldest daily backup (when there are 6)
# Keeping the last 3 backups in the directory /backup/weekly
- kind: CronJob
  apiVersion: batch/v2alpha1
  metadata:
    name: mysql-backup-weekly
  spec:
    schedule: '50 0 * * 0'
    startingDeadlineSeconds: 180
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              name: backup-weekly
          spec:
            # Application containers
            containers:
            - image: ${BACKUP_IMAGE}
              name: mysql-backup
              imagePullPolicy: Always
              volumeMounts:
              - name: mysql-backup-data
                mountPath: /backup

              env:
              - name: BACKUP_TYPE
                value: weekly
              - name: BACKUP_COUNT
                value: '3'
              - name: BACKUP_PRIOR_TYPE
                value: daily
              - name: BACKUP_PRIOR_COUNT
                value: '6'

            volumes:
            - name: mysql-backup-data
              persistentVolumeClaim:
                claimName: mysql-backup-claim
            restartPolicy: Never

# The MONTHLY CronJob (at 00:45 on the 1st of each month)
# This job will copy the oldest weekly backup (when there are 3)
# Keeping the last 11 backups in the directory /backup/monthly
- kind: CronJob
  apiVersion: batch/v2alpha1
  metadata:
    name: mysql-backup-monthly
  spec:
    schedule: '45 0 1 * *'
    startingDeadlineSeconds: 180
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              name: backup-monthly
          spec:
            # Application containers
            containers:
            - image: ${BACKUP_IMAGE}
              name: mysql-backup
              imagePullPolicy: Always
              volumeMounts:
              - name: mysql-backup-data
                mountPath: /backup

              env:
              - name: BACKUP_TYPE
                value: monthly
              - name: BACKUP_COUNT
                value: '11'
              - name: BACKUP_PRIOR_TYPE
                value: weekly
              - name: BACKUP_PRIOR_COUNT
                value: '3'

            volumes:
            - name: mysql-backup-data
              persistentVolumeClaim:
                claimName: mysql-backup-claim
            restartPolicy: Never
